### PR TITLE
(WIP) Feature: Add i18n for Home page

### PR DESCRIPTION
**Pull request by jmayalag**
Add English translation to the home page using react-i18n. #70 
I won't be able to translate everything right now, so I was thinking you could create a i18 branch where  we can continue the translation.

### CODE REVIEW

**Comment by jmayalag** [comment]
Great! I've resolved the conflicts so you should be able to merge it now.

**Comment by pA1nD** [comment]
@jmayalag do you have any suggestions for a improved translations workflow?

**Comment by jmayalag** [comment]
Once all the strings are externalized inside a translation file such as:
https://github.com/jmayalag/covid-19-py/blob/feature/i18n/src/i18n/es.js

It will be far easier to improve the translations in any language.
You could look into using this service: https://locize.com/services.html.

**Comment by pA1nD** [comment]
I'm merging this as soon as i have resolved the issues it causes in Storybook

**Comment by pA1nD** [comment]
mergin via #89

**Pull request closed without merging**
